export default {
  App: {
    text1: 'ウォレット',
    text2: '市場',
    text3: '発見する',
    text4: '私'
  },
  home: {
    text1: 'A Multi-Chain Wallet Your Assets, Your Control',
    text2: 'デジタル資産ウォレット',
    text3: 'BTC、ETH、BSC、TRON、Polkadotなどの主流の…',
    text4: '私は財布を持っている',
    text5: 'ウォレット、ハードウェア ウォレッ…',
    text6: '私は財布を持ってい',
    text7: 'ない財布を作る',
  },
  MyWallet: {
    text1: 'ネットワークを選択してください',
    text2: 'IDウォレット（HD）',
    text3: 'マルチシグウォレット',
    text4: 'KeyPalハードウェアウォレット',
    text5: 'カスタムネットワークを追加する',
  },
  WalletList: {
    text1: 'インポート方法',
    text2: 'ニーモニックを入力するかQRコードをスキャンしてインポートします。',
    text3: 'ニーモニックインポート',
    text4: 'プライベートキーがネットワークにアクセスしないようにするために、ネットワークからインポートおよびインポートします',
    text5: 'コールドウォレット',
    text6: '秘密鍵をインポートする必要はありません。インポートするアカウント番号または対応する公開鍵を入力してください。',
    text7: '財布を観察する',
  },
  walletSettings: {
    text1: 'METAMASK',
    text2: 'ウォレット設定',
    text3: '既存のウォレットのインポートまたは新規ウォレットの作成',
    text4: 'シークレットリカバリーフレーズを使用してインポートする',
    text5: 'MetaMask 拡張機能との同期',
    text6: '新しいウォレットの作成',
    text7: 'By proceeding, you agree to these',
    text8: '使用条件.',
    text9: 'MetaMask拡張に同期するには',
    text10: 'デスクトップで拡張機能を開く',
    text11: '設定／詳細設定に進む',
    text12: '[携帯電話と同期]をクリックします',
    text13: 'QRコードをスキャンして同期を開始',
    text14: 'キャンセル',
    text15: 'スキャン',
  },
  ImportQB: {
    text1: 'ニーモニックインポート',
    text2: 'ニーモニック、スペースで区切る',
    text3: '詳細モード',
    text4: 'ウォレット名',
    text5: 'パスワード',
    text6: 'パスワードを8桁以上入力してください',
    text7: 'パスワードの確認',
    text8: 'プロンプト',
    text9: 'ヒント（塗りつぶしてはいけない)',
    text10: '私は注意深く読み',
    text11: 'ユーザー規約',
    text12: '財布を導入する',
    text13: 'Mnemonics contain 12, 15, 18, 21, or 24 words',
    text14: 'この2つのパスワードは違います。再入力してください。',
    text15: 'パスワードには少なくとも8文字を含める必要があります。',
    text16: 'クリック回数が多すぎます。後でもう一度実行してください。',
    text17: 'ウォレット名の設定'
  },
  CreateWallet: {
    text1: 'スワップ',
    text2: 'プリッジ',
    text3: '相場',
    text4: 'この機能は現在の地域ではサポートされていません',
    text5: '詳細',
  },
  discover: {
    text1: 'ローカルDAppを検索するか、リンクを入力してアクセスします',
    text2: '私のDApps',
    text3: '編集',
    text4: 'DAppブラ…',
    text5: 'DAppとTIPプロトコルをブックマークする方法',
  },
  my: {
    text1: '資産の概要',
    text2: '管理財布',
    text3: '取引記録',
    text4: '友達を招待する',
    text5: 'ヘルプセンター',
    text6: '私たちについて',
    text7: 'システム設定',
    text8: 'アドレス帳',
    text9: '私',
  }
}
