export default {
  App: {
    text1: '계정',
    text2: '시장',
    text3: 'Dapps',
    text4: '마이페이지'
  },
  home: {
    text1: 'A Multi-Chain Wallet Your Assets, Your Control',
    text2: '마이페이지',
    text3: 'BTC, ETH, BSC, TRON, Polkadot와 같은 주류 공용 …',
    text4: '계정이 있습니다.',
    text5: '가져오기 지갑, 하드웨어 지갑, 다중서명…',
    text6: '계정이 없습니다.',
    text7: '계정 만들기',
  },
  MyWallet: {
    text1: '네트워크를 선택하십시오',
    text2: '네트워크를 선택하십시오',
    text3: '다중 서명 지갑',
    text4: 'KeyPal 하드웨어 지갑',
    text5: '사용자 정의 네트워크 추가',
  },
  WalletList: {
    text1: '입력 방식',
    text2: '프라이빗 키를 입력하거나 QR 코드를 스캔하여 블러 오기',
    text3: '프라이빗 키 불러 오기',
    text4: '프라이빗 키가 네트워크에 연결되지 않게 계정 불러오기',
    text5: '콜드 계정',
    text6: '계정 또는 퍼블릭 키를 입력하고 불러올 수 있습니다. 프라이빗 키를 입력 할 필요가 없습니다',
    text7: '관측 계정 모드',
  },
  ImportQB: {
    text1: '니모닉으로 불러 오기',
    text2: '니모닉',
    text3: '고급 모드',
    text4: '계정명',
    text5: '계정 비밀번호',
    text6: '최소 문자 8자 이상의 비밀번호를 입력하십시오.',
    text7: '비밀번호 확인',
    text8: '비밀번호 힌트',
    text9: '비밀번호 힌트(선택사항)',
    text10: '주의 깊게 읽었으며',
    text11: '사용자 계약',
    text12: '계정 만들기',
    text13: 'Mnemonics contain 12, 15, 18, 21, or 24 words',
    text14: '이 두 비밀번호는 다르다.다시 입력하십시오.',
    text15: '암호는 8자 이상이어야 합니다.',
    text16: '클릭 수가 너무 많아요.나중에 다시 시도하십시오.',
    text17: '지갑 이름 설정'
  },
  CreateWallet: {
    text1: '교환',
    text2: '교환',
    text3: '교환',
    text4: '이 기능은 현재 지역에서 지원되지 않습니다.',
    text5: '자세히 알아보기',
  },
  discover: {
    text1: '로컬 DApp 검색 또는 방문 링크 입력',
    text2: '내 DApps',
    text3: '내 DApps',
    text4: 'DApp 브…',
    text5: 'DApp 및 TIP 프로토콜을 북마크하는방법',
  },
  my: {
    text1: '자산 총액',
    text2: '계정 관리',
    text3: '거래 기록',
    text4: '친구 초대',
    text5: '고객 센터',
    text6: '소개',
    text7: '설정',
    text8: '주소록',
    text9: '마이페이지',
  }
}
